from schemas.common import column, system_columns


CATEGORY_NAME = "spa"

PRESENCE_KEYWORDS = [
    "spa",
    "wellness",
    "massage",
    "treatment",
    "sauna",
    "hammam",
    "thermal",
    "massaggio",
    "trattamento",
    "benessere",
]

COLUMNS = system_columns() + [
    column("ON-SITE Only - SPA Experiences Available", "enum", multi_select=True),
    column("EXPERIENCE PAGE: External Link to Spa Website", "url"),
    column("Facilities of the Spa", "enum", multi_select=True),
    column("Massage Therapy Options", "enum", multi_select=True),
    column("Facial Treatments & Skincare Options", "enum", multi_select=True),
    column("Wellness Pkgs & Spa Journey Options", "enum", multi_select=True),
    column("Wellness & Holistic Therapy Options", "enum", multi_select=True),
    column("Beauty and Grooming Options", "enum", multi_select=True),
    column("Hydrotherapy and Thermal Experience Options", "enum", multi_select=True),
    column("Name of Spa", "factual"),
    column("Address of Spa Facilities if different than hotel", "factual"),
    column("Name of Relaxation Lounge", "factual"),
    column("External Link to Relaxation Lounge", "url"),
    column("Name of Full Service Salon", "factual"),
    column("External Link to Full Service Salon", "url"),
    column("Name of Retail Boutique", "factual"),
    column("External Link to Retail Boutique", "url"),
    column("Name of Juice Bar", "factual"),
    column("External Link to Juice Bar", "url"),
    column("Name of Bistro/In-spa Dining Venue", "factual"),
    column("External Link to Bistro/In-spa Dining", "url"),
    column("Name of Yoga Studio", "factual"),
    column("External Link to Yoga Studio", "url"),
    column("OVERVIEW PAGE: Spa Headline", "editorial"),
    column("OVERVIEW PAGE: Spa Description", "editorial"),
    column("OVERVIEW PAGE: Spa Tip", "editorial"),
    column("EXPERIENCE PAGE : Spa Experience Headline", "editorial"),
    column("EXPERIENCE PAGE:  Spa Experience Description", "editorial"),
    column("SPA PAGE: Spa Headline", "editorial"),
    column("SPA PAGE: Spa Description", "editorial"),
    column("SPA PAGE: Feature Tile - Headline", "editorial"),
    column("SPA PAGE: Feature Tile - Description", "editorial"),
    column("SPA PAGE:  Customer Quote", "editorial"),
    column("SPA PAGE:  Customer Quote Attribution", "editorial"),
    column("Relaxation Lounge Headline", "editorial"),
    column("Relaxation Lounge Description", "editorial"),
    column("Full Service Salon Headline", "editorial"),
    column("Full Service Salon Description", "editorial"),
    column("Retail Boutique Headline", "editorial"),
    column("Retail Boutique Description", "editorial"),
    column("Juice Bar Headline", "editorial"),
    column("Juice Bar Description", "editorial"),
    column("Bistro/In-spa dining Headline", "editorial"),
    column("Bistro/In-spa dining Description", "editorial"),
    column("Yoga Studio Headline", "editorial"),
    column("Yoga Studio Description", "editorial"),
]

REPEATED_COLUMN_KEYS = [
    "ON-SITE Only - SPA Experiences Available",
    "EXPERIENCE PAGE: External Link to Spa Website",
    "Facilities of the Spa",
    "Massage Therapy Options",
    "Facial Treatments & Skincare Options",
    "Wellness Pkgs & Spa Journey Options",
    "Wellness & Holistic Therapy Options",
    "Beauty and Grooming Options",
    "Hydrotherapy and Thermal Experience Options",
    "Name of Spa",
    "Address of Spa Facilities if different than hotel",
    "OVERVIEW PAGE: Spa Headline",
    "OVERVIEW PAGE: Spa Description",
    "OVERVIEW PAGE: Spa Tip",
    "EXPERIENCE PAGE : Spa Experience Headline",
    "EXPERIENCE PAGE:  Spa Experience Description",
    "SPA PAGE: Spa Headline",
    "SPA PAGE: Spa Description",
    "SPA PAGE: Feature Tile - Headline",
    "SPA PAGE: Feature Tile - Description",
    "SPA PAGE:  Customer Quote",
    "SPA PAGE:  Customer Quote Attribution",
]

ELEMENTS = {
    "spa_experience": {
        "label": "Spa Experience",
        "fallback_name": "Spa Experience",
        "identifier_columns": ["Name of Spa"],
        "column_keys": [],
    },
    "relaxation_lounge": {
        "label": "Relaxation Lounge",
        "fallback_name": "Relaxation Lounge",
        "identifier_columns": ["Name of Relaxation Lounge"],
        "column_keys": [
            "Name of Relaxation Lounge",
            "External Link to Relaxation Lounge",
            "Relaxation Lounge Headline",
            "Relaxation Lounge Description",
        ],
    },
    "full_service_salon": {
        "label": "Full Service Salon",
        "fallback_name": "Full Service Salon",
        "identifier_columns": ["Name of Full Service Salon"],
        "column_keys": [
            "Name of Full Service Salon",
            "External Link to Full Service Salon",
            "Full Service Salon Headline",
            "Full Service Salon Description",
        ],
    },
    "retail_boutique": {
        "label": "Retail Boutique",
        "fallback_name": "Retail Boutique",
        "identifier_columns": ["Name of Retail Boutique"],
        "column_keys": [
            "Name of Retail Boutique",
            "External Link to Retail Boutique",
            "Retail Boutique Headline",
            "Retail Boutique Description",
        ],
    },
    "juice_bar": {
        "label": "Juice Bar",
        "fallback_name": "Juice Bar",
        "identifier_columns": ["Name of Juice Bar"],
        "column_keys": [
            "Name of Juice Bar",
            "External Link to Juice Bar",
            "Juice Bar Headline",
            "Juice Bar Description",
        ],
    },
    "bistro_in_spa_dining": {
        "label": "Bistro/In-spa Dining",
        "fallback_name": "Bistro/In-spa Dining",
        "identifier_columns": ["Name of Bistro/In-spa Dining Venue"],
        "column_keys": [
            "Name of Bistro/In-spa Dining Venue",
            "External Link to Bistro/In-spa Dining",
            "Bistro/In-spa dining Headline",
            "Bistro/In-spa dining Description",
        ],
    },
    "yoga_studio": {
        "label": "Yoga Studio",
        "fallback_name": "Yoga Studio",
        "identifier_columns": ["Name of Yoga Studio"],
        "column_keys": [
            "Name of Yoga Studio",
            "External Link to Yoga Studio",
            "Yoga Studio Headline",
            "Yoga Studio Description",
        ],
    },
}
